name: "Cloud Posture Conformity Pipeline Scanner"
description: "Scan CloudFormation files with Cloud Posture Template Scanner."
inputs:
  v1_apikey:
    description: "Vision One API Key"
    required: true
  maxExtreme:
    description: "Maximum Extreme detections accepted."
    required: false
  maxVeryHigh:
    description: "Maximum Very High detections accepted."
    required: false
  maxHigh:
    description: "Maximum High detections accepted."
    required: false
  maxMedium:
    description: "Maximum Medium detections accepted."
    required: false
  maxLow:
    description: "Maximum Low detections accepted."
    required: false
  templatePath:
    description: "Location of the file to be scanned, eg templates/template.yml."
    required: true
  templatesDirPath:
    description: "(Optional) Location of the directory of templates to be scanned, (e.g., templates). This ignores the value of 'templatePath' if supplied."
    required: false
branding:
  icon: "check"
  color: "red"
runs:
    using: 'node16'
    main: 'scan.js'